### ISSUE TITLE
PLEX "Playback Error: Could not tune channel. Please check your tuner or antenna."

### ISSUE THREAD

**Issue by puv** [jfarseneau/antennas#91]
Hi,
I have encountered an issue where once I start loading a channel, after approx 5 seconds it just throws me an error saying `"Could not tune channel. Please check your tuner or antenna."`
I am running Antennas on Docker on a Raspberry Pi 4B.

In antennas logs, I see plex sending two requests, nothing more.
```  <-- GET /discover.json
  --> GET /discover.json 200 2ms 394b
  <-- GET /lineup_status.json
  --> GET /lineup_status.json 200 2ms 77b
```
  
In TVHeadend, it seems that plex requests to see a channel, but then stops soon after, there are no errors whatsoever apart from that.
```2022-06-09 13:45:00.168 [   INFO] mpegts: jp.m3u - AT-X (720p) [Not 24/7] in Japan - tuning on IPTV #1
2022-06-09 13:45:00.752 [   INFO] subscription: 0008: "HTTP" subscribing on channel "AT-X", weight: 150, adapter: "IPTV #1", network: "Japan", mux: "jp.m3u - AT-X (720p) [Not 24/7]", provider: "FFmpeg", service: "Service01", profile="matroska", hostname="192.168.68.10", client="Lavf/58.65.101"
2022-06-09 13:45:05.410 [   INFO] subscription: 0008: "HTTP" unsubscribing from "AT-X", hostname="192.168.68.10", client="Lavf/58.65.101"
```

As for Plex logs, there seems to be nothing.
Any help would be greatly appreciated!!

**Comment by puv** [comment]
Silly me, spent like 12 hours searching for a fix and just realized to use the "pass" profile.

**Comment by Shazib** [comment]
Hi @puv - sorry to necro - can you provide anymore info on this? i'm having the same error. The URLs in lineup.json work fine in VLC, i've disabled every profile expect 'pass' in tvheadend but still get this error in plex

I even sometimes get a flicker of the live feed for half a second, just a still, before it errors out.

**Comment by Shazib** [comment]
Silly me as well! This is because the browser can't support MPEG-2, it works on the android TV app.

**Comment by zhongfu** [comment]
ran into this issue too, because I had a streaming profile that muxes the stream into a Matroska container set as the global default

didn't work even though I had set the "pass" profile as the default for the user I used for HDHomeRun emulation -- it would just default to the Matroska profile, which would cause Plex Transcoder to fail (resulting in the "Could not tune channel" error)

turns out, I had to also select "Streaming profiles" in the "Change parameters" field (duh) for the user. without that, it just won't apply the defaults you've configured for the user
